"""
App name → Android package name mapping with fuzzy fallback.
Standalone copy, no project dependencies.
"""
import difflib

PACKAGE_MAP = {
    "天气": "com.coloros.weather2",
    "家人守护": "com.coloros.familyguard",
    "美柚": "com.lingan.seeyou",
    "百度极速版": "com.baidu.searchbox.lite",
    "58同城": "com.wuba",
    "知乎": "com.zhihu.android",
    "滴滴出行": "com.sdu.didi.psnger",
    "计算器": "com.coloros.calculator",
    "掌上生活": "com.cmbchina.ccd.pluto.cmbActivity",
    "飞猪旅行": "com.taobao.trip",
    "网易有道词典": "com.youdao.dict",
    "百度贴吧": "com.baidu.tieba",
    "腾讯新闻": "com.tencent.news",
    "饿了么": "me.ele",
    "百度输入法": "com.baidu.input",
    "优酷视频": "com.youku.phone",
    "抖音": "com.ss.android.ugc.aweme",
    "今日头条": "com.ss.android.article.news",
    "酷我音乐": "cn.kuwo.player",
    "夸克": "com.quark.browser",
    "邮件": "com.android.email",
    "美团": "com.sankuai.meituan",
    "剪映": "com.lemon.lv",
    "酷狗音乐": "com.kugou.android",
    "网易邮箱大师": "com.netease.mail",
    "番茄免费小说": "com.dragon.read",
    "qq": "com.tencent.mobileqq",
    "小宇宙": "app.podcast.cosmos",
    "指南针": "com.coloros.compass2",
    "天猫": "com.tmall.wireless",
    "录音": "com.coloros.soundrecorder",
    "哔哩哔哩": "tv.danmaku.bili",
    "B站": "tv.danmaku.bili",
    "soul": "cn.soulapp.android",
    "高德地图": "com.autonavi.minimap",
    "小红书": "com.xingin.xhs",
    "拼多多": "com.xunmeng.pinduoduo",
    "微信读书": "com.tencent.weread",
    "大众点评": "com.dianping.v1",
    "云闪付": "com.unionpay",
    "qq浏览器": "com.tencent.mtt",
    "文件管理": "com.coloros.filemanager",
    "豆瓣": "com.douban.frodo",
    "日历": "com.coloros.calendar",
    "网易云音乐": "com.netease.cloudmusic",
    "喜马拉雅": "com.ximalaya.ting.android",
    "飞书": "com.ss.android.lark",
    "全民K歌": "com.tencent.karaoke",
    "美图秀秀": "com.mt.mtxx.mtxx",
    "时钟": "com.coloros.alarmclock",
    "钱包": "com.finshell.wallet",
    "快手极速版": "com.kuaishou.nebula",
    "微博": "com.sina.weibo",
    "墨迹天气": "com.moji.mjweather",
    "kimi 智能助手": "com.moonshot.kimichat",
    "豆包": "com.larus.nova",
    "去哪儿旅行": "com.Qunar",
    "腾讯地图": "com.tencent.map",
    "芒果TV": "com.hunantv.imgo.activity",
    "便签": "com.coloros.note",
    "UC浏览器": "com.UCMobile",
    "百度文库": "com.baidu.wenku",
    "腾讯文档": "com.tencent.docs",
    "携程旅行": "ctrip.android.view",
    "wpsoffice": "cn.wps.moffice_eng",
    "哈啰": "com.jingyao.easybike",
    "中国移动": "com.greenpoint.android.mc10086.activity",
    "唯品会": "com.achievo.vipshop",
    "汽水音乐": "com.luna.music",
    "支付宝": "com.eg.android.AlipayGphone",
    "爱奇艺": "com.qiyi.video",
    "西瓜视频": "com.ss.android.article.video",
    "网易新闻": "com.netease.newsreader.activity",
    "腾讯视频": "com.tencent.qqlive",
    "淘宝": "com.taobao.taobao",
    "快手": "com.smile.gifmaker",
    "菜鸟": "com.cainiao.wireless",
    "盒马": "com.wudaokou.hippo",
    "闲鱼": "com.taobao.idlefish",
    "搜狗输入法": "com.sohu.inputmethod.sogou",
    "QQ邮箱": "com.tencent.androidqqmail",
    "百度网盘": "com.baidu.netdisk",
    "QQ音乐": "com.tencent.qqmusic",
    "百度": "com.baidu.searchbox",
    "抖音极速版": "com.ss.android.ugc.aweme.lite",
    "铁路12306": "com.MobileTicket",
    "掌阅": "com.chaozh.iReaderFree",
    "腾讯会议": "com.tencent.wemeet.app",
    "企业微信": "com.tencent.wework",
    "微信": "com.tencent.mm",
    "京东": "com.jingdong.app.mall",
    "百度地图": "com.baidu.BaiduMap",
    "大麦": "cn.damai",
    "设置": "com.android.settings",
    "王者荣耀": "com.tencent.tmgp.sgame",
    "随手记": "com.mymoney",
    "猫眼": "com.sankuai.movie",
    "航旅纵横": "com.umetrip.android.msky.app",
    "学习强国": "cn.xuexi.android",
    "浏览器": "com.android.browser",
    "瑞幸咖啡": "com.lucky.luckyclient",
    "钉钉": "com.alibaba.android.rimet",
    "同程旅行": "com.tongcheng.android",
    "keep": "com.gotokeep.keep",
    "蜻蜓FM": "fm.qingting.qtradio",
    "虎牙直播": "com.duowan.kiwi",
    "转转": "com.wuba.zhuanzhuan",
    "扫描全能王": "com.intsig.camscanner",
    "得物": "com.shizhuang.duapp",
    "阿里巴巴": "com.alibaba.wireless",
    "游戏中心": "com.nearme.gamecenter",
    "百词斩": "com.jiongji.andriod.card",
    "企查查": "com.android.icredit",
    "opentracks": "de.dennisguse.opentracks",
    "joplin": "net.cozic.joplin",
    "audio recorder": "com.dimowner.audiorecorder",
    "markor": "net.gsantner.markor",
    "tasks": "org.tasks",
}


def find_package_name(app_name: str) -> str:
    """Return package name for app_name, with fuzzy fallback."""
    key = app_name.strip().lower()
    # Build a lowercase-key index for case-insensitive exact match
    lower_map = {k.lower(): v for k, v in PACKAGE_MAP.items()}
    if key in lower_map:
        return lower_map[key]

    best_key = max(
        lower_map.keys(),
        key=lambda k: difflib.SequenceMatcher(None, key, k).ratio(),
    )
    pkg = lower_map[best_key]
    print(f"[package_map] fuzzy match: '{app_name}' → '{best_key}' → {pkg}")
    return pkg
